apiVersion: v1
kind: Pod
metadata:
  name: aro-key-vault-app
  namespace: default
spec:
  containers:
  - name: aro-key-vault-app
    image: acrj8ba3.azurecr.io/aro-key-vault-app:latest
    volumeMounts:
      - name: secrets-store-inline
        mountPath: "/mnt/secrets-store"
        readOnly: true
  imagePullSecrets:
  - name: acr-secret
  volumes:
    - name: secrets-store-inline
      csi:
        driver: secrets-store.csi.k8s.io
        readOnly: true
        volumeAttributes:
          secretProviderClass: "azure-kvname"
        nodePublishSecretRef:
          name: secrets-store-creds
