apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: azure-kvname
  namespace: default
spec:
  provider: azure
  secretObjects:
  - secretName: kv-secrets
    type: Opaque
    data:
    - objectName: ENV-TYPE
      key: ENV-TYPE
    - objectName: AZURE-TENANT-ID
      key: AZURE-TENANT-ID
    - objectName: AZURE-CLIENT-ID
      key: AZURE-CLIENT-ID
    - objectName: AZURE-CLIENT-SECRET
      key: AZURE-CLIENT-SECRET
    - objectName: PG-SERVER
      key: PG-SERVER
    - objectName: PG-DATABASE
      key: PG-DATABASE
    - objectName: PG-USER
      key: PG-USER
  parameters:
    usePodIdentity: "false"
    useVMManagedIdentity: "false"
    userAssignedIdentityID: ""
    keyvaultName: "kv-aro-test"
    objects: |
      array:
        - |
          objectName: ENV-TYPE
          objectType: secret
          objectVersion: ""
        - |
          objectName: AZURE-TENANT-ID
          objectType: secret
          objectVersion: ""
        - |
          objectName: AZURE-CLIENT-ID
          objectType: secret
          objectVersion: ""
        - |
          objectName: AZURE-CLIENT-SECRET
          objectType: secret
          objectVersion: ""
        - |
          objectName: PG-SERVER
          objectType: secret
          objectVersion: ""
        - |
          objectName: PG-DATABASE
          objectType: secret
          objectVersion: ""
        - |
          objectName: PG-USER
          objectType: secret
          objectVersion: ""
  tenantId: "<AZURE_TENANT_ID>"
